// Dispatch.cpp : Defines the exported functions for the DLL application.
//

#include "stdafx.h"

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class storage_Dispatch */

#ifndef _Included_storage_Dispatch
#define _Included_storage_Dispatch
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     storage_Dispatch
	* Method:    read_ports
	* Signature: ([I[I)V
	*/
	JNIEXPORT void JNICALL Java_storage_Dispatch_read_1ports(JNIEnv *, jobject, jintArray, jintArray) {
		printf("ta a ler\n");
	}

	/*
	* Class:     storage_Dispatch
	* Method:    move
	* Signature: (C)V
	*/
	JNIEXPORT void JNICALL Java_storage_Dispatch_move(JNIEnv *, jobject, jchar) {
		printf("ta a mover\n");
	}

#ifdef __cplusplus
}
#endif
#endif
