/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardware_Hardware */

#ifndef _Included_hardware_Hardware
#define _Included_hardware_Hardware
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hardware_Hardware
 * Method:    create_di
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hardware_Hardware_create_channels
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardware_Hardware
 * Method:    write_port
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hardware_Hardware_write_port
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hardware_Hardware
 * Method:    read_port
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hardware_Hardware_read_port
  (JNIEnv *, jobject, jint);

/*
 * Class:     hardware_Hardware
 * Method:    set_bit
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hardware_Hardware_set_bit
  (JNIEnv *, jobject, jint port, jint bit, jint value);

/*
* Class:     hardware_Hardware
* Method:    get_bit
* Signature: (II)I
*/
JNIEXPORT jboolean JNICALL Java_hardware_Hardware_get_bit
  (JNIEnv *, jobject, jint port, jint bit);

#ifdef __cplusplus
}
#endif
#endif
